version: "3.8"
services:
  hapi-server:
    container_name: hapi-server
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - postgres-db
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - ${PORT}
    volumes:
      - ./src:/hapi-server/src
      - ./nodemon.json:/hapi-server/nodemon.json
    command: npm run dev
    restart: always
  postgres-db:
    build:
      context: ./postgres-database
      dockerfile: Dockerfile
    ports:
      - ${POSTGRES_PORT}-${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
