version: "3.8"
services:
  nestjs-server:
    container_name: veronika-server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - veronika-network
    depends_on:
      - postgres-db
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - ${PORT}
    volumes:
      - ./logs:/server/logs
      - ./nodemon.json:/server/nodemon.json
    restart: on-failure
  postgres-db:
    container_name: veronika-postgres-db
    build:
      context: ./postgres-database
      dockerfile: Dockerfile
    networks:
      - veronika-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: on-failure
networks:
  veronika-network:
    name: veronika-network
    driver: bridge
volumes:
  pgdata:
  logs:
